### ISSUE TITLE
[Contracts] optimisations

### ISSUE THREAD

**Issue by bitbeckers** [protocol/hypercerts-protocol#14]
As a Solidity developer, I want to evaluate the contracts to implement gas cost optimisations so that execution of contract calls becomes cheapers.

End of milestone V0.1

- [x] Inspect gas reported
- [x] E.g. refactor loops
- [x] Inspect mappings and structs
- [x] Review uint ranges
- [ ] Memory/calldata
- [ ] Variable packing
- [x] Gas cost looping over structs passed between methods
- [x] Split parse from mint for more flexible updating
- [ ] ...

**Comment by moconnell** [comment]
inlining the unpack data fn does appear to save smol amt gas

pre:
[hypercerts_pre_inline](https://user-images.githubusercontent.com/640958/186658235-0484d42e-dc46-43f2-b968-c60cfc9446b4.png)

post:
[hypercerts_post_inline](https://user-images.githubusercontent.com/640958/186658230-54614e50-6283-47b6-80f9-46ab9d76f45e.png)

**Comment by bitbeckers** [comment]
Gas at start of PR

<img width="819" alt="Screenshot 2022-09-01 at 15 17 42" src="https://user-images.githubusercontent.com/19667964/187923525-d5b46686-ada9-414f-82a4-d79a013d5d2b.png">
